name: Build

on:
  push:
    branches: [main]
    paths-ignore:
      - 'CHANGELOG.md'
      - 'version.txt'
      - '.release-please-manifest.json'

jobs:
  build:
    uses: mistre83/shared-workflows/.github/workflows/build.yml@main
    permissions:
      id-token: write
      contents: read
    secrets: inherit

  release-please:
    needs: build
    uses: mistre83/shared-workflows/.github/workflows/release-please.yml@main
    secrets: inherit
